# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java Continuos Disintegration :-) building with Maven

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      java-distribution:
        required: true
        type: string
      file-pom:
        required: true
        type: string
      environment-message:
        required: true
        type: string
      environment-secret:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.token }}
    - name: Show banner message
      run: echo "Message from above - ${{ inputs.environment-message }}"
    - name: Show a second message
      run: echo "using thjis confidential value - [${{ inputs.environment-secret }}]"
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file ${{ inputs.file-pom }}

